# -*- coding: utf-8 -*-
"""MultiplyTheMatrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MS6C46lph1wk0DLFH_d0Z19MJcOve-aW
"""

import numpy as np


print("*** Welcome To this program *** ")
print("please enter matrix1 dim that your want:")
x=[ int(x) for x in input("Enter dim: ").split() ]
Matrix1=[]
for i in range(x[0]):
  exec(f'm1ls{i} =[ int(x) for x in input("Enter row: ").split() ]' )
  exec(f'Matrix1.append(m1ls{i})')

print("please enter matrix2 dim that your want:")
y=[ int(x) for x in input("Enter dim: ").split() ]
Matrix2=[]
for i in range(y[0]):
  exec(f'm2ls{i} =[ int(x) for x in input("Enter row: ").split() ]' )
  exec(f'Matrix2.append(m2ls{i})')

result=np.zeros((x[0],y[1])) 

if(x[1]!=y[0]):
  print("error")
else:
  for i in range(len(Matrix1)):
   # iterate through columns of Y
   for j in range(len(Matrix2[0])):
       # iterate through rows of Y
       for k in range(len(Matrix2)):
           result[i][j] += Matrix1[i][k] * Matrix2[k][j]
  
print("---------------")
print("Input")
for i in range(len(Matrix1)):
     print(*Matrix1[i])
print("---------------")
for i in range(len(Matrix2)):
     print(*Matrix2[i])
print("---------------")
print("output")
for r in result:
    print(r)